[
  {
    id: 1,
    name: "제주대학교병원",
    address1: "제주특별자치도",
    address2: "제주시",
    address3: "아란13길 15",
    phone: "064-717-1114",
    type: "GENERAL",
    officeHours: "09:00~17:00",
    isPopular: true,
    isCurrentlyOpen: true,
    latitude: 33.4734,
    longitude: 126.5021,
    isFavorite: true,
    engName: "Jeju National University Hospital",
    engAddress: "Jeju Special Self-Governing Province, Jeju-si, ARan13-gil, 15",
  },
  {
    id: 2,
    name: "제주한라병원",
    address1: "제주특별자치도",
    address2: "제주시",
    address3: "도령로 65",
    phone: "064-740-5000",
    type: "GENERAL",
    officeHours: "09:00~17:00",
    isPopular: true,
    isCurrentlyOpen: true,
    latitude: 33.489,
    longitude: 126.4983,
    isFavorite: true,
    engName: "Jeju Halla Hospital",
    engAddress:
      "Jeju Special Self-Governing Province, Jeju-si, Doryeong-ro, 65",
  },
  {
    id: 3,
    name: "제주도립병원",
    address1: "제주특별자치도",
    address2: "제주시",
    address3: "월산로 387",
    phone: "064-750-9000",
    type: "GENERAL",
    officeHours: "09:00~17:00",
    isPopular: true,
    isCurrentlyOpen: true,
    latitude: 33.4845,
    longitude: 126.4728,
    isFavorite: false,
    engName: "Jeju Provincial Hospital",
    engAddress: "Jeju Special Self-Governing Province, Jeju-si, Wolsan-ro, 387",
  },
  {
    id: 4,
    name: "한국병원",
    address1: "제주특별자치도",
    address2: "제주시",
    address3: "서광로 193",
    phone: "064-750-0000",
    type: "GENERAL",
    officeHours: "09:00~17:00",
    isPopular: true,
    isCurrentlyOpen: true,
    latitude: 33.4996,
    longitude: 126.5312,
    isFavorite: false,
    engName: "Hanguk Hospital",
    engAddress:
      "Jeju Special Self-Governing Province, Jeju-si, Seogwang-ro, 193",
  },
  {
    id: 5,
    name: "제주시내과의원",
    address1: "제주특별자치도",
    address2: "제주시",
    address3: "중앙로 123",
    phone: "064-123-4567",
    type: "INTERNAL",
    officeHours: "09:00~17:00",
    isPopular: false,
    isCurrentlyOpen: true,
    latitude: 33.5009,
    longitude: 126.5221,
    isFavorite: false,
    engName: "Jeju-si Internal Medicine Clinic",
    engAddress:
      "Jeju Special Self-Governing Province, Jeju-si, Jungang-ro, 123",
  },
  {
    id: 6,
    name: "제주소아과",
    address1: "제주특별자치도",
    address2: "제주시",
    address3: "삼도이동 234",
    phone: "064-234-5678",
    type: "PEDIATRICS",
    officeHours: "09:00~18:00",
    isPopular: false,
    isCurrentlyOpen: true,
    latitude: 33.5023,
    longitude: 126.5234,
    isFavorite: false,
    engName: "Jeju Pediatrics",
    engAddress:
      "Jeju Special Self-Governing Province, Jeju-si, Samdo-2-dong, 234",
  },
  {
    id: 7,
    name: "제주정형외과",
    address1: "제주특별자치도",
    address2: "제주시",
    address3: "일도이동 345",
    phone: "064-345-6789",
    type: "ORTHOPEDICS",
    officeHours: "09:00~17:30",
    isPopular: false,
    isCurrentlyOpen: true,
    latitude: 33.5045,
    longitude: 126.5267,
    isFavorite: false,
    engName: "Jeju Orthopedics",
    engAddress:
      "Jeju Special Self-Governing Province, Jeju-si, Ildo-2-dong, 345",
  },
  {
    id: 8,
    name: "제주산부인과",
    address1: "제주특별자치도",
    address2: "제주시",
    address3: "용담삼동 456",
    phone: "064-456-7890",
    type: "OB_GYN",
    officeHours: "09:00~17:00",
    isPopular: false,
    isCurrentlyOpen: true,
    latitude: 33.5123,
    longitude: 126.5189,
    isFavorite: false,
    engName: "Jeju Obstetrics & Gynecology",
    engAddress:
      "Jeju Special Self-Governing Province, Jeju-si, Yongdam-3-dong, 456",
  },
  {
    id: 9,
    name: "제주이비인후과",
    address1: "제주특별자치도",
    address2: "제주시",
    address3: "건입동 567",
    phone: "064-567-8901",
    type: "ENT",
    officeHours: "09:00~17:00",
    isPopular: false,
    isCurrentlyOpen: true,
    latitude: 33.4978,
    longitude: 126.5134,
    isFavorite: false,
    engName: "Jeju Otorhinolaryngology",
    engAddress:
      "Jeju Special Self-Governing Province, Jeju-si, Geonip-dong, 567",
  },
  {
    id: 10,
    name: "제주안과",
    address1: "제주특별자치도",
    address2: "제주시",
    address3: "오라이동 678",
    phone: "064-678-9012",
    type: "OPHTHALMOLOGY",
    officeHours: "09:00~17:00",
    isPopular: false,
    isCurrentlyOpen: true,
    latitude: 33.4856,
    longitude: 126.4923,
    isFavorite: false,
    engName: "Jeju Eye Clinic",
    engAddress:
      "Jeju Special Self-Governing Province, Jeju-si, Ora-2-dong, 678",
  },
  {
    id: 11,
    name: "제주가정의학과",
    address1: "제주특별자치도",
    address2: "제주시",
    address3: "노형동 789",
    phone: "064-789-0123",
    type: "GENERAL",
    officeHours: "09:00~17:00",
    isPopular: false,
    isCurrentlyOpen: null,
    latitude: 33.4745,
    longitude: 126.4812,
    isFavorite: false,
    engName: "Jeju Family Medicine",
    engAddress:
      "Jeju Special Self-Governing Province, Jeju-si, Nohyeong-dong, 789",
  },
  {
    id: 12,
    name: "제주피부과",
    address1: "제주특별자치도",
    address2: "제주시",
    address3: "연동 890",
    phone: "064-890-1234",
    type: "DERMATOLOGY",
    officeHours: "09:00~18:00",
    isPopular: false,
    isCurrentlyOpen: true,
    latitude: 33.4892,
    longitude: 126.4756,
    isFavorite: false,
    engName: "Jeju Dermatology",
    engAddress: "Jeju Special Self-Governing Province, Jeju-si, Yeon-dong, 890",
  },
  {
    id: 13,
    name: "제주치과병원",
    address1: "제주특별자치도",
    address2: "제주시",
    address3: "이도일동 901",
    phone: "064-901-2345",
    type: "DENTAL",
    officeHours: "09:00~18:00",
    isPopular: true,
    isCurrentlyOpen: true,
    latitude: 33.5067,
    longitude: 126.5278,
    isFavorite: false,
    engName: "Jeju Dental Hospital",
    engAddress:
      "Jeju Special Self-Governing Province, Jeju-si, Ido-1-dong, 901",
  },
  {
    id: 14,
    name: "제주신경과",
    address1: "제주특별자치도",
    address2: "제주시",
    address3: "삼도삼동 012",
    phone: "064-012-3456",
    type: "NEUROLOGY",
    officeHours: "09:00~17:00",
    isPopular: false,
    isCurrentlyOpen: true,
    latitude: 33.5134,
    longitude: 126.5301,
    isFavorite: false,
    engName: "Jeju Neurology",
    engAddress:
      "Jeju Special Self-Governing Province, Jeju-si, Samdo-3-dong, 012",
  },
  {
    id: 15,
    name: "제주정신건강의학과",
    address1: "제주특별자치도",
    address2: "제주시",
    address3: "용담일동 123",
    phone: "064-123-4567",
    type: "PSYCHIATRY",
    officeHours: "09:00~17:00",
    isPopular: false,
    isCurrentlyOpen: true,
    latitude: 33.5156,
    longitude: 126.5123,
    isFavorite: false,
    engName: "Jeju Psychiatry",
    engAddress:
      "Jeju Special Self-Governing Province, Jeju-si, Yongdam-1-dong, 123",
  },
  {
    id: 16,
    name: "제주비뇨의학과",
    address1: "제주특별자치도",
    address2: "제주시",
    address3: "화북일동 234",
    phone: "064-234-5678",
    type: "UROLOGY",
    officeHours: "09:00~17:30",
    isPopular: false,
    isCurrentlyOpen: true,
    latitude: 33.5234,
    longitude: 126.5445,
    isFavorite: false,
    engName: "Jeju Urology",
    engAddress:
      "Jeju Special Self-Governing Province, Jeju-si, Hwabuk-1-dong, 234",
  },
  {
    id: 17,
    name: "제주외과의원",
    address1: "제주특별자치도",
    address2: "제주시",
    address3: "이호일동 345",
    phone: "064-345-6789",
    type: "SURGERY",
    officeHours: "09:00~17:00",
    isPopular: false,
    isCurrentlyOpen: null,
    latitude: 33.5067,
    longitude: 126.4578,
    isFavorite: false,
    engName: "Jeju Surgery Clinic",
    engAddress:
      "Jeju Special Self-Governing Province, Jeju-si, Iho-1-dong, 345",
  },
  {
    id: 18,
    name: "제주재활의학과",
    address1: "제주특별자치도",
    address2: "제주시",
    address3: "도두일동 456",
    phone: "064-456-7890",
    type: "REHABILITATION",
    officeHours: "09:00~18:00",
    isPopular: false,
    isCurrentlyOpen: true,
    latitude: 33.5123,
    longitude: 126.4689,
    isFavorite: false,
    engName: "Jeju Rehabilitation Medicine",
    engAddress:
      "Jeju Special Self-Governing Province, Jeju-si, Dodu-1-dong, 456",
  },
  {
    id: 19,
    name: "제주영상의학과",
    address1: "제주특별자치도",
    address2: "제주시",
    address3: "화북이동 567",
    phone: "064-567-8901",
    type: "RADIOLOGY",
    officeHours: "09:00~17:00",
    isPopular: false,
    isCurrentlyOpen: true,
    latitude: 33.5234,
    longitude: 126.5567,
    isFavorite: false,
    engName: "Jeju Radiology",
    engAddress:
      "Jeju Special Self-Governing Province, Jeju-si, Hwabuk-2-dong, 567",
  },
  {
    id: 20,
    name: "제주한의원",
    address1: "제주특별자치도",
    address2: "제주시",
    address3: "아라일동 678",
    phone: "064-678-9012",
    type: "ORIENTAL",
    officeHours: "09:00~18:00",
    isPopular: false,
    isCurrentlyOpen: true,
    latitude: 33.4734,
    longitude: 126.5021,
    isFavorite: false,
    engName: "Jeju Korean Medicine Clinic",
    engAddress:
      "Jeju Special Self-Governing Province, Jeju-si, Ara-1-dong, 678",
  },
  {
    id: 21,
    name: "제주응급의학과",
    address1: "제주특별자치도",
    address2: "제주시",
    address3: "연동 789",
    phone: "064-789-0123",
    type: "EMERGENCY",
    officeHours: "24:00~24:00",
    isPopular: true,
    isCurrentlyOpen: true,
    latitude: 33.4892,
    longitude: 126.4756,
    isFavorite: false,
    engName: "Jeju Emergency Medicine",
    engAddress: "Jeju Special Self-Governing Province, Jeju-si, Yeon-dong, 789",
  },
  {
    id: 22,
    name: "제주마취통증의학과",
    address1: "제주특별자치도",
    address2: "제주시",
    address3: "오라삼동 890",
    phone: "064-890-1234",
    type: "ANESTHESIOLOGY",
    officeHours: "09:00~17:00",
    isPopular: false,
    isCurrentlyOpen: true,
    latitude: 33.4856,
    longitude: 126.4923,
    isFavorite: false,
    engName: "Jeju Anesthesiology & Pain Medicine",
    engAddress:
      "Jeju Special Self-Governing Province, Jeju-si, Ora-3-dong, 890",
  },
  {
    id: 23,
    name: "제주내분비내과",
    address1: "제주특별자치도",
    address2: "제주시",
    address3: "노형동 901",
    phone: "064-901-2345",
    type: "ENDOCRINOLOGY",
    officeHours: "09:00~17:00",
    isPopular: false,
    isCurrentlyOpen: null,
    latitude: 33.4745,
    longitude: 126.4812,
    isFavorite: false,
    engName: "Jeju Endocrinology",
    engAddress:
      "Jeju Special Self-Governing Province, Jeju-si, Nohyeong-dong, 901",
  },
  {
    id: 24,
    name: "제주심장내과",
    address1: "제주특별자치도",
    address2: "제주시",
    address3: "일도이동 012",
    phone: "064-012-3456",
    type: "CARDIOLOGY",
    officeHours: "09:00~17:30",
    isPopular: false,
    isCurrentlyOpen: true,
    latitude: 33.5045,
    longitude: 126.5267,
    isFavorite: false,
    engName: "Jeju Cardiology",
    engAddress:
      "Jeju Special Self-Governing Province, Jeju-si, Ildo-2-dong, 012",
  },
  {
    id: 25,
    name: "제주호흡기내과",
    address1: "제주특별자치도",
    address2: "제주시",
    address3: "삼도이동 123",
    phone: "064-123-4567",
    type: "PULMONOLOGY",
    officeHours: "09:00~17:00",
    isPopular: false,
    isCurrentlyOpen: true,
    latitude: 33.5023,
    longitude: 126.5234,
    isFavorite: false,
    engName: "Jeju Pulmonology",
    engAddress:
      "Jeju Special Self-Governing Province, Jeju-si, Samdo-2-dong, 123",
  },
  {
    id: 26,
    name: "제주소화기내과",
    address1: "제주특별자치도",
    address2: "제주시",
    address3: "용담삼동 234",
    phone: "064-234-5678",
    type: "GASTROENTEROLOGY",
    officeHours: "09:00~18:00",
    isPopular: false,
    isCurrentlyOpen: true,
    latitude: 33.5123,
    longitude: 126.5189,
    isFavorite: false,
    engName: "Jeju Gastroenterology",
    engAddress:
      "Jeju Special Self-Governing Province, Jeju-si, Yongdam-3-dong, 234",
  },
  {
    id: 27,
    name: "제주혈관외과",
    address1: "제주특별자치도",
    address2: "제주시",
    address3: "건입동 345",
    phone: "064-345-6789",
    type: "VASCULAR_SURGERY",
    officeHours: "09:00~17:00",
    isPopular: false,
    isCurrentlyOpen: null,
    latitude: 33.4978,
    longitude: 126.5134,
    isFavorite: false,
    engName: "Jeju Vascular Surgery",
    engAddress:
      "Jeju Special Self-Governing Province, Jeju-si, Geonip-dong, 345",
  },
  {
    id: 28,
    name: "제주흉부외과",
    address1: "제주특별자치도",
    address2: "제주시",
    address3: "이도일동 456",
    phone: "064-456-7890",
    type: "THORACIC_SURGERY",
    officeHours: "09:00~17:00",
    isPopular: false,
    isCurrentlyOpen: true,
    latitude: 33.5067,
    longitude: 126.5278,
    isFavorite: false,
    engName: "Jeju Thoracic Surgery",
    engAddress:
      "Jeju Special Self-Governing Province, Jeju-si, Ido-1-dong, 456",
  },
  {
    id: 29,
    name: "제주신장내과",
    address1: "제주특별자치도",
    address2: "제주시",
    address3: "삼도삼동 567",
    phone: "064-567-8901",
    type: "NEPHROLOGY",
    officeHours: "09:00~17:30",
    isPopular: false,
    isCurrentlyOpen: true,
    latitude: 33.5134,
    longitude: 126.5301,
    isFavorite: false,
    engName: "Jeju Nephrology",
    engAddress:
      "Jeju Special Self-Governing Province, Jeju-si, Samdo-3-dong, 567",
  },
  {
    id: 30,
    name: "제주류마티스내과",
    address1: "제주특별자치도",
    address2: "제주시",
    address3: "용담일동 678",
    phone: "064-678-9012",
    type: "RHEUMATOLOGY",
    officeHours: "09:00~17:00",
    isPopular: false,
    isCurrentlyOpen: true,
    latitude: 33.5156,
    longitude: 126.5123,
    isFavorite: false,
    engName: "Jeju Rheumatology",
    engAddress:
      "Jeju Special Self-Governing Province, Jeju-si, Yongdam-1-dong, 678",
  },
  {
    id: 31,
    name: "제주감염내과",
    address1: "제주특별자치도",
    address2: "제주시",
    address3: "화북일동 789",
    phone: "064-789-0123",
    type: "INFECTIOUS_DISEASE",
    officeHours: "09:00~18:00",
    isPopular: false,
    isCurrentlyOpen: true,
    latitude: 33.5234,
    longitude: 126.5445,
    isFavorite: false,
    engName: "Jeju Infectious Disease",
    engAddress:
      "Jeju Special Self-Governing Province, Jeju-si, Hwabuk-1-dong, 789",
  },
  {
    id: 32,
    name: "제주종양내과",
    address1: "제주특별자치도",
    address2: "제주시",
    address3: "이호일동 890",
    phone: "064-890-1234",
    type: "ONCOLOGY",
    officeHours: "09:00~17:00",
    isPopular: true,
    isCurrentlyOpen: true,
    latitude: 33.5067,
    longitude: 126.4578,
    isFavorite: false,
    engName: "Jeju Oncology",
    engAddress:
      "Jeju Special Self-Governing Province, Jeju-si, Iho-1-dong, 890",
  },
  {
    id: 33,
    name: "제주알레르기내과",
    address1: "제주특별자치도",
    address2: "제주시",
    address3: "도두일동 901",
    phone: "064-901-2345",
    type: "ALLERGY",
    officeHours: "09:00~17:00",
    isPopular: false,
    isCurrentlyOpen: null,
    latitude: 33.5123,
    longitude: 126.4689,
    isFavorite: false,
    engName: "Jeju Allergy",
    engAddress:
      "Jeju Special Self-Governing Province, Jeju-si, Dodu-1-dong, 901",
  },
  {
    id: 34,
    name: "제주핵의학과",
    address1: "제주특별자치도",
    address2: "제주시",
    address3: "화북이동 012",
    phone: "064-012-3456",
    type: "NUCLEAR_MEDICINE",
    officeHours: "09:00~17:00",
    isPopular: false,
    isCurrentlyOpen: true,
    latitude: 33.5234,
    longitude: 126.5567,
    isFavorite: false,
    engName: "Jeju Nuclear Medicine",
    engAddress:
      "Jeju Special Self-Governing Province, Jeju-si, Hwabuk-2-dong, 012",
  },
  {
    id: 35,
    name: "제주병리과",
    address1: "제주특별자치도",
    address2: "제주시",
    address3: "아라일동 123",
    phone: "064-123-4567",
    type: "PATHOLOGY",
    officeHours: "09:00~17:00",
    isPopular: false,
    isCurrentlyOpen: true,
    latitude: 33.4734,
    longitude: 126.5021,
    isFavorite: false,
    engName: "Jeju Pathology",
    engAddress:
      "Jeju Special Self-Governing Province, Jeju-si, Ara-1-dong, 123",
  },
  {
    id: 36,
    name: "제주진단검사의학과",
    address1: "제주특별자치도",
    address2: "제주시",
    address3: "연동 234",
    phone: "064-234-5678",
    type: "LABORATORY_MEDICINE",
    officeHours: "09:00~18:00",
    isPopular: false,
    isCurrentlyOpen: true,
    latitude: 33.4892,
    longitude: 126.4756,
    isFavorite: false,
    engName: "Jeju Laboratory Medicine",
    engAddress: "Jeju Special Self-Governing Province, Jeju-si, Yeon-dong, 234",
  },
  {
    id: 37,
    name: "제주예방의학과",
    address1: "제주특별자치도",
    address2: "제주시",
    address3: "오라삼동 345",
    phone: "064-345-6789",
    type: "PREVENTIVE_MEDICINE",
    officeHours: "09:00~17:00",
    isPopular: false,
    isCurrentlyOpen: null,
    latitude: 33.4856,
    longitude: 126.4923,
    isFavorite: false,
    engName: "Jeju Preventive Medicine",
    engAddress:
      "Jeju Special Self-Governing Province, Jeju-si, Ora-3-dong, 345",
  },
  {
    id: 38,
    name: "제주직업환경의학과",
    address1: "제주특별자치도",
    address2: "제주시",
    address3: "노형동 456",
    phone: "064-456-7890",
    type: "OCCUPATIONAL_MEDICINE",
    officeHours: "09:00~17:00",
    isPopular: false,
    isCurrentlyOpen: true,
    latitude: 33.4745,
    longitude: 126.4812,
    isFavorite: false,
    engName: "Jeju Occupational Medicine",
    engAddress:
      "Jeju Special Self-Governing Province, Jeju-si, Nohyeong-dong, 456",
  },
  {
    id: 39,
    name: "제주성형외과",
    address1: "제주특별자치도",
    address2: "제주시",
    address3: "일도이동 567",
    phone: "064-567-8901",
    type: "PLASTIC_SURGERY",
    officeHours: "09:00~18:00",
    isPopular: false,
    isCurrentlyOpen: true,
    latitude: 33.5045,
    longitude: 126.5267,
    isFavorite: false,
    engName: "JeJuSeongHyeongxx",
    engAddress:
      "Jeju Special Self-Governing Province, Jeju-si, Ildo-2-dong, 567",
  },
  {
    id: 40,
    name: "제주응급센터",
    address1: "제주특별자치도",
    address2: "제주시",
    address3: "삼도이동 678",
    phone: "064-678-9012",
    type: "EMERGENCY",
    officeHours: "24:00~24:00",
    isPopular: false,
    isCurrentlyOpen: true,
    latitude: 33.5023,
    longitude: 126.5234,
    isFavorite: false,
    engName: "JeJuxxxx",
    engAddress:
      "Jeju Special Self-Governing Province, Jeju-si, Samdo-2-dong, 678",
  },
  {
    id: 41,
    name: "365플러스내과의원",
    address1: "제주특별자치도",
    address2: "서귀포시",
    address3: "일주동로 9159, 4층 (법환동)",
    phone: "064-767-3650",
    type: "INTERNAL",
    officeHours: "09:00~17:00",
    isPopular: false,
    isCurrentlyOpen: true,
    latitude: 33.3105938,
    longitude: 126.726177,
    isFavorite: true,
    engName: "365 Plus Internal Medicine Clinic",
    engAddress:
      "Jeju Special Self-Governing Province, Seogwipo-si, Iljudong-ro, 9159, 4F, (xHwan-dong)",
  },
  {
    id: 42,
    name: "서귀포의료원",
    address1: "제주특별자치도",
    address2: "서귀포시",
    address3: "중앙로 47",
    phone: "064-730-3000",
    type: "GENERAL",
    officeHours: "09:00~17:00",
    isPopular: true,
    isCurrentlyOpen: true,
    latitude: 33.2452,
    longitude: 126.5622,
    isFavorite: true,
    engName: "Seogwipo Medical Center",
    engAddress:
      "Jeju Special Self-Governing Province, Seogwipo-si, Jungang-ro, 47",
  },
  {
    id: 43,
    name: "서귀포제일병원",
    address1: "제주특별자치도",
    address2: "서귀포시",
    address3: "태평로 439",
    phone: "064-739-3000",
    type: "GENERAL",
    officeHours: "09:00~17:00",
    isPopular: true,
    isCurrentlyOpen: true,
    latitude: 33.2523,
    longitude: 126.5634,
    isFavorite: false,
    engName: "Seogwipo Jeil Hospital",
    engAddress:
      "Jeju Special Self-Governing Province, Seogwipo-si, Taepyeong-ro, 439",
  },
  {
    id: 44,
    name: "서귀포내과의원",
    address1: "제주특별자치도",
    address2: "서귀포시",
    address3: "동홍동 456",
    phone: "064-732-1234",
    type: "INTERNAL",
    officeHours: "09:00~17:00",
    isPopular: false,
    isCurrentlyOpen: true,
    latitude: 33.2467,
    longitude: 126.5678,
    isFavorite: false,
    engName: "Seogwipo Internal Medicine Clinic",
    engAddress:
      "Jeju Special Self-Governing Province, Seogwipo-si, DongHong-dong, 456",
  },
  {
    id: 45,
    name: "서귀포소아과",
    address1: "제주특별자치도",
    address2: "서귀포시",
    address3: "서귀동 567",
    phone: "064-733-2345",
    type: "PEDIATRICS",
    officeHours: "09:00~18:00",
    isPopular: false,
    isCurrentlyOpen: true,
    latitude: 33.2489,
    longitude: 126.5701,
    isFavorite: false,
    engName: "Seogwipo Pediatrics",
    engAddress:
      "Jeju Special Self-Governing Province, Seogwipo-si, Seogwi-dong, 567",
  },
  {
    id: 46,
    name: "중문정형외과",
    address1: "제주특별자치도",
    address2: "서귀포시",
    address3: "중문동 123",
    phone: "064-738-1111",
    type: "ORTHOPEDICS",
    officeHours: "09:00~17:30",
    isPopular: false,
    isCurrentlyOpen: true,
    latitude: 33.2567,
    longitude: 126.4123,
    isFavorite: false,
    engName: "Jungmun Orthopedics",
    engAddress:
      "Jeju Special Self-Governing Province, Seogwipo-si, Jungmun-dong, 123",
  },
  {
    id: 47,
    name: "서귀포산부인과",
    address1: "제주특별자치도",
    address2: "서귀포시",
    address3: "보목동 789",
    phone: "064-739-2222",
    type: "OB_GYN",
    officeHours: "09:00~17:00",
    isPopular: false,
    isCurrentlyOpen: true,
    latitude: 33.2345,
    longitude: 126.4567,
    isFavorite: false,
    engName: "Seogwipo Obstetrics & Gynecology",
    engAddress:
      "Jeju Special Self-Governing Province, Seogwipo-si, Bomok-dong, 789",
  },
  {
    id: 48,
    name: "성산이비인후과",
    address1: "제주특별자치도",
    address2: "서귀포시",
    address3: "성산읍 234",
    phone: "064-784-3333",
    type: "ENT",
    officeHours: "09:00~17:00",
    isPopular: false,
    isCurrentlyOpen: true,
    latitude: 33.4567,
    longitude: 126.8901,
    isFavorite: false,
    engName: "Seongsan Otorhinolaryngology",
    engAddress:
      "Jeju Special Self-Governing Province, Seogwipo-si, Seongsan-eup, 234",
  },
  {
    id: 49,
    name: "서귀포안과의원",
    address1: "제주특별자치도",
    address2: "서귀포시",
    address3: "칠십리로 345",
    phone: "064-732-4444",
    type: "OPHTHALMOLOGY",
    officeHours: "09:00~17:00",
    isPopular: false,
    isCurrentlyOpen: true,
    latitude: 33.2678,
    longitude: 126.5234,
    isFavorite: false,
    engName: "Seogwipo Eye Clinic",
    engAddress:
      "Jeju Special Self-Governing Province, Seogwipo-si, Chilsimni-ro, 345",
  },
  {
    id: 50,
    name: "표선가정의학과",
    address1: "제주특별자치도",
    address2: "서귀포시",
    address3: "표선면 456",
    phone: "064-787-5555",
    type: "GENERAL",
    officeHours: "09:00~17:00",
    isPopular: false,
    isCurrentlyOpen: null,
    latitude: 33.3234,
    longitude: 126.8345,
    isFavorite: false,
    engName: "Pyoseon Family Medicine",
    engAddress:
      "Jeju Special Self-Governing Province, Seogwipo-si, Pyoseon-myeon, 456",
  },
  {
    id: 51,
    name: "서귀포피부과",
    address1: "제주특별자치도",
    address2: "서귀포시",
    address3: "대포동 567",
    phone: "064-738-6666",
    type: "DERMATOLOGY",
    officeHours: "09:00~18:00",
    isPopular: false,
    isCurrentlyOpen: true,
    latitude: 33.2456,
    longitude: 126.4678,
    isFavorite: false,
    engName: "Seogwipo Dermatology",
    engAddress:
      "Jeju Special Self-Governing Province, Seogwipo-si, Daepo-dong, 567",
  },
  {
    id: 52,
    name: "남원신경과의원",
    address1: "제주특별자치도",
    address2: "서귀포시",
    address3: "남원읍 678",
    phone: "064-764-7777",
    type: "NEUROLOGY",
    officeHours: "09:00~17:00",
    isPopular: false,
    isCurrentlyOpen: true,
    latitude: 33.2789,
    longitude: 126.7123,
    isFavorite: false,
    engName: "Namwon Neurology Clinic",
    engAddress:
      "Jeju Special Self-Governing Province, Seogwipo-si, Namwon-eup, 678",
  },
  {
    id: 53,
    name: "서귀포치과병원",
    address1: "제주특별자치도",
    address2: "서귀포시",
    address3: "송산동 789",
    phone: "064-733-8888",
    type: "DENTAL",
    officeHours: "09:00~18:00",
    isPopular: true,
    isCurrentlyOpen: true,
    latitude: 33.2567,
    longitude: 126.5456,
    isFavorite: false,
    engName: "Seogwipo Dental Hospital",
    engAddress:
      "Jeju Special Self-Governing Province, Seogwipo-si, Songsan-dong, 789",
  },
  {
    id: 54,
    name: "안덕정신건강의학과",
    address1: "제주특별자치도",
    address2: "서귀포시",
    address3: "안덕면 890",
    phone: "064-794-9999",
    type: "PSYCHIATRY",
    officeHours: "09:00~17:00",
    isPopular: false,
    isCurrentlyOpen: true,
    latitude: 33.289,
    longitude: 126.3123,
    isFavorite: false,
    engName: "Andeok Psychiatry",
    engAddress:
      "Jeju Special Self-Governing Province, Seogwipo-si, Andeok-myeon, 890",
  },
  {
    id: 55,
    name: "서귀포비뇨의학과",
    address1: "제주특별자치도",
    address2: "서귀포시",
    address3: "토평동 901",
    phone: "064-735-0000",
    type: "UROLOGY",
    officeHours: "09:00~17:30",
    isPopular: false,
    isCurrentlyOpen: true,
    latitude: 33.2345,
    longitude: 126.5678,
    isFavorite: false,
    engName: "Seogwipo Urology",
    engAddress:
      "Jeju Special Self-Governing Province, Seogwipo-si, Tox-dong, 901",
  },
  {
    id: 56,
    name: "대정외과의원",
    address1: "제주특별자치도",
    address2: "서귀포시",
    address3: "대정읍 012",
    phone: "064-794-1111",
    type: "SURGERY",
    officeHours: "09:00~17:00",
    isPopular: false,
    isCurrentlyOpen: null,
    latitude: 33.2123,
    longitude: 126.2456,
    isFavorite: false,
    engName: "Daejeong Surgery Clinic",
    engAddress:
      "Jeju Special Self-Governing Province, Seogwipo-si, Daejeong-eup, 012",
  },
  {
    id: 57,
    name: "서귀포재활의학과",
    address1: "제주특별자치도",
    address2: "서귀포시",
    address3: "효돈동 123",
    phone: "064-737-2222",
    type: "REHABILITATION",
    officeHours: "09:00~18:00",
    isPopular: false,
    isCurrentlyOpen: true,
    latitude: 33.2678,
    longitude: 126.5901,
    isFavorite: false,
    engName: "Seogwipo Rehabilitation Medicine",
    engAddress:
      "Jeju Special Self-Governing Province, Seogwipo-si, Hyodon-dong, 123",
  },
  {
    id: 58,
    name: "중문영상의학과",
    address1: "제주특별자치도",
    address2: "서귀포시",
    address3: "색달동 234",
    phone: "064-738-3333",
    type: "RADIOLOGY",
    officeHours: "09:00~17:00",
    isPopular: false,
    isCurrentlyOpen: true,
    latitude: 33.2456,
    longitude: 126.4234,
    isFavorite: false,
    engName: "Jungmun Radiology",
    engAddress:
      "Jeju Special Self-Governing Province, Seogwipo-si, Saekdal-dong, 234",
  },
  {
    id: 59,
    name: "서귀포한의원",
    address1: "제주특별자치도",
    address2: "서귀포시",
    address3: "정방동 345",
    phone: "064-732-4444",
    type: "ORIENTAL",
    officeHours: "09:00~18:00",
    isPopular: false,
    isCurrentlyOpen: true,
    latitude: 33.2234,
    longitude: 126.5567,
    isFavorite: false,
    engName: "Seogwipo Korean Medicine Clinic",
    engAddress:
      "Jeju Special Self-Governing Province, Seogwipo-si, Jeongbang-dong, 345",
  },
  {
    id: 60,
    name: "성산응급의학과",
    address1: "제주특별자치도",
    address2: "서귀포시",
    address3: "성산읍 456",
    phone: "064-784-5555",
    type: "EMERGENCY",
    officeHours: "24:00~24:00",
    isPopular: true,
    isCurrentlyOpen: true,
    latitude: 33.4789,
    longitude: 126.9123,
    isFavorite: false,
    engName: "Seongsan Emergency Medicine",
    engAddress:
      "Jeju Special Self-Governing Province, Seogwipo-si, Seongsan-eup, 456",
  },
  {
    id: 61,
    name: "서귀포마취통증의학과",
    address1: "제주특별자치도",
    address2: "서귀포시",
    address3: "천지동 567",
    phone: "064-739-6666",
    type: "ANESTHESIOLOGY",
    officeHours: "09:00~17:00",
    isPopular: false,
    isCurrentlyOpen: true,
    latitude: 33.2567,
    longitude: 126.5234,
    isFavorite: false,
    engName: "Seogwipo Anesthesiology & Pain Medicine",
    engAddress:
      "Jeju Special Self-Governing Province, Seogwipo-si, Cheonji-dong, 567",
  },
  {
    id: 62,
    name: "표선내분비내과",
    address1: "제주특별자치도",
    address2: "서귀포시",
    address3: "표선면 678",
    phone: "064-787-7777",
    type: "ENDOCRINOLOGY",
    officeHours: "09:00~17:00",
    isPopular: false,
    isCurrentlyOpen: null,
    latitude: 33.3456,
    longitude: 126.8567,
    isFavorite: false,
    engName: "Pyoseon Endocrinology",
    engAddress:
      "Jeju Special Self-Governing Province, Seogwipo-si, Pyoseon-myeon, 678",
  },
  {
    id: 63,
    name: "남원심장내과",
    address1: "제주특별자치도",
    address2: "서귀포시",
    address3: "남원읍 789",
    phone: "064-764-8888",
    type: "CARDIOLOGY",
    officeHours: "09:00~17:30",
    isPopular: false,
    isCurrentlyOpen: true,
    latitude: 33.289,
    longitude: 126.7234,
    isFavorite: false,
    engName: "Namwon Cardiology",
    engAddress:
      "Jeju Special Self-Governing Province, Seogwipo-si, Namwon-eup, 789",
  },
  {
    id: 64,
    name: "서귀포호흡기내과",
    address1: "제주특별자치도",
    address2: "서귀포시",
    address3: "동홍동 890",
    phone: "064-733-9999",
    type: "PULMONOLOGY",
    officeHours: "09:00~17:00",
    isPopular: false,
    isCurrentlyOpen: true,
    latitude: 33.2345,
    longitude: 126.5789,
    isFavorite: false,
    engName: "Seogwipo Pulmonology",
    engAddress:
      "Jeju Special Self-Governing Province, Seogwipo-si, DongHong-dong, 890",
  },
  {
    id: 65,
    name: "안덕소화기내과",
    address1: "제주특별자치도",
    address2: "서귀포시",
    address3: "안덕면 901",
    phone: "064-794-0000",
    type: "GASTROENTEROLOGY",
    officeHours: "09:00~18:00",
    isPopular: false,
    isCurrentlyOpen: true,
    latitude: 33.3012,
    longitude: 126.3456,
    isFavorite: false,
    engName: "Andeok Gastroenterology",
    engAddress:
      "Jeju Special Self-Governing Province, Seogwipo-si, Andeok-myeon, 901",
  },
  {
    id: 66,
    name: "서귀포혈관외과",
    address1: "제주특별자치도",
    address2: "서귀포시",
    address3: "서귀동 012",
    phone: "064-732-1111",
    type: "VASCULAR_SURGERY",
    officeHours: "09:00~17:00",
    isPopular: false,
    isCurrentlyOpen: null,
    latitude: 33.2456,
    longitude: 126.5678,
    isFavorite: false,
    engName: "Seogwipo Vascular Surgery",
    engAddress:
      "Jeju Special Self-Governing Province, Seogwipo-si, Seogwi-dong, 012",
  },
  {
    id: 67,
    name: "대정흉부외과",
    address1: "제주특별자치도",
    address2: "서귀포시",
    address3: "대정읍 123",
    phone: "064-794-2222",
    type: "THORACIC_SURGERY",
    officeHours: "09:00~17:00",
    isPopular: false,
    isCurrentlyOpen: true,
    latitude: 33.2234,
    longitude: 126.2678,
    isFavorite: false,
    engName: "Daejeong Thoracic Surgery",
    engAddress:
      "Jeju Special Self-Governing Province, Seogwipo-si, Daejeong-eup, 123",
  },
  {
    id: 68,
    name: "서귀포신장내과",
    address1: "제주특별자치도",
    address2: "서귀포시",
    address3: "법정동 234",
    phone: "064-738-3333",
    type: "NEPHROLOGY",
    officeHours: "09:00~17:30",
    isPopular: false,
    isCurrentlyOpen: true,
    latitude: 33.2678,
    longitude: 126.4901,
    isFavorite: false,
    engName: "Seogwipo Nephrology",
    engAddress:
      "Jeju Special Self-Governing Province, Seogwipo-si, Beopjeong-dong, 234",
  },
  {
    id: 69,
    name: "중문류마티스내과",
    address1: "제주특별자치도",
    address2: "서귀포시",
    address3: "중문동 345",
    phone: "064-738-4444",
    type: "RHEUMATOLOGY",
    officeHours: "09:00~17:00",
    isPopular: false,
    isCurrentlyOpen: true,
    latitude: 33.2567,
    longitude: 126.4123,
    isFavorite: false,
    engName: "Jungmun Rheumatology",
    engAddress:
      "Jeju Special Self-Governing Province, Seogwipo-si, Jungmun-dong, 345",
  },
  {
    id: 70,
    name: "성산감염내과",
    address1: "제주특별자치도",
    address2: "서귀포시",
    address3: "성산읍 456",
    phone: "064-784-5555",
    type: "INFECTIOUS_DISEASE",
    officeHours: "09:00~18:00",
    isPopular: false,
    isCurrentlyOpen: true,
    latitude: 33.4901,
    longitude: 126.9345,
    isFavorite: false,
    engName: "Seongsan Infectious Disease",
    engAddress:
      "Jeju Special Self-Governing Province, Seogwipo-si, Seongsan-eup, 456",
  },
  {
    id: 71,
    name: "서귀포종양내과",
    address1: "제주특별자치도",
    address2: "서귀포시",
    address3: "보목동 567",
    phone: "064-739-6666",
    type: "ONCOLOGY",
    officeHours: "09:00~17:00",
    isPopular: true,
    isCurrentlyOpen: true,
    latitude: 33.2345,
    longitude: 126.4567,
    isFavorite: false,
    engName: "Seogwipo Oncology",
    engAddress:
      "Jeju Special Self-Governing Province, Seogwipo-si, Bomok-dong, 567",
  },
  {
    id: 72,
    name: "표선알레르기내과",
    address1: "제주특별자치도",
    address2: "서귀포시",
    address3: "표선면 678",
    phone: "064-787-7777",
    type: "ALLERGY",
    officeHours: "09:00~17:00",
    isPopular: false,
    isCurrentlyOpen: null,
    latitude: 33.3567,
    longitude: 126.8789,
    isFavorite: false,
    engName: "Pyoseon Allergy",
    engAddress:
      "Jeju Special Self-Governing Province, Seogwipo-si, Pyoseon-myeon, 678",
  },
  {
    id: 73,
    name: "남원핵의학과",
    address1: "제주특별자치도",
    address2: "서귀포시",
    address3: "남원읍 789",
    phone: "064-764-8888",
    type: "NUCLEAR_MEDICINE",
    officeHours: "09:00~17:00",
    isPopular: false,
    isCurrentlyOpen: true,
    latitude: 33.2789,
    longitude: 126.7456,
    isFavorite: false,
    engName: "Namwon Nuclear Medicine",
    engAddress:
      "Jeju Special Self-Governing Province, Seogwipo-si, Namwon-eup, 789",
  },
  {
    id: 74,
    name: "서귀포병리과",
    address1: "제주특별자치도",
    address2: "서귀포시",
    address3: "동홍동 890",
    phone: "064-733-9999",
    type: "PATHOLOGY",
    officeHours: "09:00~17:00",
    isPopular: false,
    isCurrentlyOpen: true,
    latitude: 33.2456,
    longitude: 126.5901,
    isFavorite: false,
    engName: "Seogwipo Pathology",
    engAddress:
      "Jeju Special Self-Governing Province, Seogwipo-si, DongHong-dong, 890",
  },
  {
    id: 75,
    name: "안덕진단검사의학과",
    address1: "제주특별자치도",
    address2: "서귀포시",
    address3: "안덕면 901",
    phone: "064-794-0000",
    type: "LABORATORY_MEDICINE",
    officeHours: "09:00~18:00",
    isPopular: false,
    isCurrentlyOpen: true,
    latitude: 33.3123,
    longitude: 126.3678,
    isFavorite: false,
    engName: "Andeok Laboratory Medicine",
    engAddress:
      "Jeju Special Self-Governing Province, Seogwipo-si, Andeok-myeon, 901",
  },
  {
    id: 76,
    name: "서귀포예방의학과",
    address1: "제주특별자치도",
    address2: "서귀포시",
    address3: "서귀동 012",
    phone: "064-732-1111",
    type: "PREVENTIVE_MEDICINE",
    officeHours: "09:00~17:00",
    isPopular: false,
    isCurrentlyOpen: null,
    latitude: 33.2567,
    longitude: 126.5234,
    isFavorite: false,
    engName: "Seogwipo Preventive Medicine",
    engAddress:
      "Jeju Special Self-Governing Province, Seogwipo-si, Seogwi-dong, 012",
  },
  {
    id: 77,
    name: "대정직업환경의학과",
    address1: "제주특별자치도",
    address2: "서귀포시",
    address3: "대정읍 123",
    phone: "064-794-2222",
    type: "OCCUPATIONAL_MEDICINE",
    officeHours: "09:00~17:00",
    isPopular: false,
    isCurrentlyOpen: true,
    latitude: 33.2345,
    longitude: 126.2901,
    isFavorite: false,
    engName: "Daejeong Occupational Medicine",
    engAddress:
      "Jeju Special Self-Governing Province, Seogwipo-si, Daejeong-eup, 123",
  },
  {
    id: 78,
    name: "서귀포임상약리학과",
    address1: "제주특별자치도",
    address2: "서귀포시",
    address3: "법정동 234",
    phone: "064-738-3333",
    type: "CLINICAL_PHARMACOLOGY",
    officeHours: "09:00~17:30",
    isPopular: false,
    isCurrentlyOpen: true,
    latitude: 33.2789,
    longitude: 126.5123,
    isFavorite: false,
    engName: "Seogwipo Clinical Pharmacology",
    engAddress:
      "Jeju Special Self-Governing Province, Seogwipo-si, Beopjeong-dong, 234",
  },
  {
    id: 79,
    name: "중문성형외과",
    address1: "제주특별자치도",
    address2: "서귀포시",
    address3: "중문동 345",
    phone: "064-738-4444",
    type: "PLASTIC_SURGERY",
    officeHours: "09:00~18:00",
    isPopular: true,
    isCurrentlyOpen: true,
    latitude: 33.2456,
    longitude: 126.4234,
    isFavorite: false,
    engName: "Jungmun Plastic Surgery",
    engAddress:
      "Jeju Special Self-Governing Province, Seogwipo-si, Jungmun-dong, 345",
  },
  {
    id: 80,
    name: "성산응급센터",
    address1: "제주특별자치도",
    address2: "서귀포시",
    address3: "성산읍 456",
    phone: "064-784-5555",
    type: "EMERGENCY",
    officeHours: "24:00~24:00",
    isPopular: true,
    isCurrentlyOpen: true,
    latitude: 33.5012,
    longitude: 126.9567,
    isFavorite: false,
    engName: "Seongsan Emergency Center",
    engAddress:
      "Jeju Special Self-Governing Province, Seogwipo-si, Seongsan-eup, 456",
  },
];
