import type { Metadata } from "next";
import "@/styles/global.css";
import React from "react";
import { LocaleProvider } from "@/app/_components/provider/LocaleProvider";
import { cookies } from "next/headers";
import { Locale } from "@/libs/i18n";
import loadTranslation from "@/libs/i18n/utils/loadTranslation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const serverLocale = ((await cookies()).get("lng")?.value || "en") as Locale;
  const localeJson = await loadTranslation(serverLocale);

  return (
    <html lang="en">
      <head>
        <script
          type="text/javascript"
          src={`https://oapi.map.naver.com/openapi/v3/maps.js?ncpKeyId=${process.env.NEXT_PUBLIC_NAVER_MAPS_CLIENT_ID}`}
          async
        />
      </head>
      <body>
        <LocaleProvider value={{ localeJson, serverLocale }}>
          {children}
        </LocaleProvider>
      </body>
    </html>
  );
}
