import type { Metadata } from "next";
import React from "react";
import { LocaleProvider } from "@/app/_components/provider/LocaleProvider";
import { cookies } from "next/headers";
import { Locale } from "@/libs/i18n";
import loadTranslation from "@/libs/i18n/utils/loadTranslation";
import "@/styles/global.css";
import {
  getServerSideCookie,
  setServerSideCookie,
} from "@/utils/server/cookies";
import { HStack, VStack } from "@vapor-ui/core";
import { DashboardHeader } from "@/app/dashboard/_components/DashboardHeader";
import {
  MOBILE_FRAME_HEIGHT,
  MOBILE_FRAME_WIDTH,
} from "@/app/_constants/index.constants";

export const metadata: Metadata = {
  title: "Medi Line",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const serverLocale = ((await getServerSideCookie("lng")) || "en") as Locale;

  const localeJson = await loadTranslation(serverLocale);

  return (
    <html lang="en">
      <head>
        <script
          type="text/javascript"
          src={`https://oapi.map.naver.com/openapi/v3/maps.js?ncpKeyId=729vqxwwt0`}
          async
        />
      </head>
      <body>
        <LocaleProvider value={{ localeJson, serverLocale }}>
          <HStack
            width={"100%"}
            height={"100vh"}
            justifyContent="center"
            alignItems="center"
            backgroundColor={"$white"}
          >
            <VStack
              width={MOBILE_FRAME_WIDTH}
              height={MOBILE_FRAME_HEIGHT}
              backgroundColor={"#$gray-050"}
            >
              {children}
            </VStack>
          </HStack>
        </LocaleProvider>
      </body>
    </html>
  );
}
